disabled_rules:
  - force_cast
  - identifier_name
  - leading_whitespace
  - trailing_whitespace
  - void_return
  - cyclomatic_complexity
  - implicit_getter
  - trailing_newline
  - syntactic_sugar
  - literal_expression_end_indentation
  - colon
  - implicitly_unwrapped_optional
  - nesting
  - unused_closure_parameter
  - discarded_notification_center_observer
  - operator_whitespace
  - function_body_length
  - orphaned_doc_comment
excluded:
  - Submodules/
  - Carthage/
  - vendor/bundle
opt_in_rules:
  - implicit_return
  - mark
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiple_closures_with_trailing_closure
  - private_outlet
  - sorted_imports
  - strong_iboutlet
  - switch_case_alignment
  - switch_case_on_newline
  - unneeded_break_in_switch
  - unused_import
  - closure_spacing
  - empty_string
  - fatal_error_message
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_parameters
  - override_in_extension
  - required_enum_case
  - yoda_condition
file_length:
  warning: 800
  error: 1000000000
line_length:
  ignores_comments: true
  warning: 150
  error: 1000000000
type_body_length:
  warning: 500
  error: 1000000000
