whitelist_rules:
  - comma
  - trailing_comma
  - vertical_whitespace
  - implicit_return
  - sorted_imports
  - unused_import
  - closure_spacing
  - switch_case_alignment
  - switch_case_on_newline
excluded:
  - Submodules/
  - Carthage/
  - vendor/bundle