disabled_rules: # rule identifiers to exclude from running
- colon
- force_cast
- line_length
operator_usage_whitespace: true
override_in_extension: true
private_action: true
private_outlet: true
required_enum_case: true
sorted_imports: true
strict_fileprivate: true
switch_case_on_newline: true
trailing_closure: true
unneeded_parentheses_in_closure_argument: true
unused_optional_binding: true
vertical_parameter_alignment: true
vertical_parameter_alignment_on_call: true
yoda_condition: true
excluded:
- Submodules/