configs:
  Debug Dev: debug
  Debug Production: debug
  Debug Staging: debug
  Release: release
  Release Staging: release
name: Modules
options:
  bundleIdPrefix: com.blockchain
  defaultConfig: Release
  deploymentTarget:
    iOS: '11.0'
  groupSortPosition: top
  platform: iOS
settings:
  SUPPORTS_MACCATALYST: false
  VALID_ARCHS: arm64
  VALID_ARCHS[sdk=iphonesimulator*]: x86_64
targetTemplates:
  Framework:
    platform: iOS
    sources:
    - ${target_name}
    type: framework
  FrameworkTest:
    dependencies:
    - target: TestKit
    - carthage: RxSwift
    - carthage: RxBlocking
    - carthage: RxTest
    platform: iOS
    sources:
    - ${target_name}
    type: bundle.unit-test
targets:
  BitcoinKit:
    dependencies:
    - target: PlatformKit
    - target: ToolKit
    - target: NetworkKit
    - carthage: BigInt
    - carthage: RxSwift
    - carthage: LibWally
    scheme:
      testTargets:
      - BitcoinKitTests
    templates:
    - Framework
  BitcoinKitTests:
    dependencies:
    - target: BitcoinKit
    templates:
    - FrameworkTest
  CommonCryptoKit:
    scheme:
      testTargets:
      - CommonCryptoKitTests
    templates:
    - Framework
  CommonCryptoKitTests:
    dependencies:
    - target: CommonCryptoKit
    templates:
    - FrameworkTest
  ERC20Kit:
    dependencies:
    - target: NetworkKit
    - target: EthereumKit
    - target: PlatformKit
    - carthage: RxCocoa
    - carthage: RxSwift
    - carthage: RxRelay
    - carthage: BigInt
    - carthage: web3swift
    scheme:
      testTargets:
      - ERC20KitTests
    templates:
    - Framework
  ERC20KitTests:
    dependencies:
    - target: ERC20Kit
    templates:
    - FrameworkTest
  EthereumKit:
    dependencies:
    - target: NetworkKit
    - target: PlatformKit
    - carthage: keccak
    - carthage: PromiseKit
    - carthage: BigInt
    - carthage: secp256k1
    - carthage: web3swift
    - carthage: scrypt
    - carthage: RxSwift
    - carthage: RxRelay
    scheme:
      testTargets:
      - EthereumKitTests
    templates:
    - Framework
  EthereumKitTests:
    dependencies:
    - target: EthereumKit
    templates:
    - FrameworkTest
  HDWalletKit:
    dependencies:
    - target: CommonCryptoKit
    - carthage: LibWally
    scheme:
      testTargets:
      - HDWalletKitTests
    templates:
    - Framework
  HDWalletKitTests:
    dependencies:
    - target: HDWalletKit
    templates:
    - FrameworkTest
  Localization:
    templates:
    - Framework
  NetworkKit:
    dependencies:
    - carthage: RxSwift
    - target: ToolKit
    scheme:
      testTargets:
      - NetworkKitTests
    templates:
    - Framework
  NetworkKitTests:
    dependencies:
    - target: NetworkKit
    templates:
    - FrameworkTest
  PlatformKit:
    dependencies:
    - target: CommonCryptoKit
    - target: Localization
    - target: NetworkKit
    - target: ToolKit
    - carthage: BigInt
    - carthage: RxSwift
    - carthage: RxRelay
    - carthage: RxCocoa
    scheme:
      testTargets:
      - PlatformKitTests
    templates:
    - Framework
  PlatformKitTests:
    dependencies:
    - target: PlatformKit
    templates:
    - FrameworkTest
  PlatformUIKit:
    dependencies:
    - target: Localization
    - target: PlatformKit
    - target: ToolKit
    - carthage: BigInt
    - carthage: Charts
    - carthage: PhoneNumberKit
    - carthage: RxSwift
    - carthage: RxRelay
    - carthage: RxCocoa
    - carthage: Zxcvbn
    scheme:
      testTargets:
      - PlatformUIKitTests
    templates:
    - Framework
  PlatformUIKitTests:
    dependencies:
    - target: PlatformUIKit
    templates:
    - FrameworkTest
  StellarKit:
    dependencies:
    - target: PlatformKit
    - carthage: RxCocoa
    - carthage: RxSwift
    - carthage: stellarsdk
    scheme:
      testTargets:
      - StellarKitTests
    templates:
    - Framework
  StellarKitTests:
    dependencies:
    - target: StellarKit
    templates:
    - FrameworkTest
  TestKit:
    templates:
    - Framework
  ToolKit:
    dependencies:
    - carthage: BigInt
    - carthage: RxSwift
    - carthage: RxRelay
    scheme:
      testTargets:
      - ToolKitTests
    templates:
    - Framework
  ToolKitTests:
    dependencies:
    - target: ToolKit
    templates:
    - FrameworkTest
