attributes:
  ORGANIZATIONNAME: Blockchain Luxembourg S.A
configs:
  Debug Dev: debug
  Debug Production: debug
  Debug Staging: debug
  Release: release
  Release Staging: release
name: Blockchain
options:
  bundleIdPrefix: com.rainydayapps
  defaultConfig: Release
  deploymentTarget:
    iOS: '11.0'
  groupSortPosition: top
  platform: iOS
schemeTemplates:
  BlockchainScheme:
    analyze:
      config: ${debugConfig}
    archive:
      config: ${releaseConfig}
      customArchiveName: Blockchain
    build:
      targets:
        Blockchain: build
    profile:
      config: ${releaseConfig}
    run:
      config: ${debugConfig}
    test:
      config: ${debugConfig}
      targets:
      - name: BlockchainTests
        parallelizable: true
        randomExecutionOrder: true
      - name: BitcoinKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: CommonCryptoKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: ERC20KitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: EthereumKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: HDWalletKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: NetworkKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: PlatformKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: PlatformUIKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: StellarKitTests
        parallelizable: true
        randomExecutionOrder: true
      - name: ToolKitTests
        parallelizable: true
        randomExecutionOrder: true
schemes:
  Blockchain:
    templateAttributes:
      debugConfig: Debug Production
      releaseConfig: Release
    templates:
    - BlockchainScheme
  Blockchain (Dev):
    templateAttributes:
      debugConfig: Debug Dev
      releaseConfig: Release
    templates:
    - BlockchainScheme
  Blockchain (Staging):
    templateAttributes:
      debugConfig: Debug Staging
      releaseConfig: Release Staging
    templates:
    - BlockchainScheme
settingGroups:
  base_ios:
    base:
      TARGETED_DEVICE_FAMILY: 1
  base_signing:
    base:
      CODE_SIGN_ENTITLEMENTS: Blockchain/Blockchain.entitlements
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: NZ6PH75U7K
  debug_signing:
    base:
      CODE_SIGN_IDENTITY: iPhone Developer
      PROVISIONING_PROFILE_SPECIFIER: match Development com.rainydayapps.Blockchain
    groups:
    - base_signing
  release_signing:
    base:
      CODE_SIGN_IDENTITY: iPhone Distribution
      PROVISIONING_PROFILE_SPECIFIER: match AppStore com.rainydayapps.Blockchain
    groups:
    - base_signing
settings:
  base:
    CODE_SIGN_STYLE: Manual
    ENABLE_BITCODE: false
    SUPPORTS_MACCATALYST: false
    VALID_ARCHS: arm64
    VALID_ARCHS[sdk=iphonesimulator*]: x86_64
targetTemplates:
  Framework:
    platform: iOS
    sources:
    - excludes:
      - Scripts
      path: ${target_name}
    type: framework
  FrameworkTest:
    dependencies:
    - target: TestKit
    - carthage: RxSwift
    - carthage: RxBlocking
    - carthage: RxTest
    platform: iOS
    sources:
    - ${target_name}
    type: bundle.unit-test
targets:
  BitcoinKit:
    dependencies:
    - target: PlatformKit
    - target: ToolKit
    - target: NetworkKit
    - carthage: BigInt
    - carthage: RxSwift
    - carthage: LibWally
    scheme:
      testTargets:
      - BitcoinKitTests
    templates:
    - Framework
  BitcoinKitTests:
    dependencies:
    - target: BitcoinKit
    templates:
    - FrameworkTest
  Blockchain:
    configFiles:
      Debug Dev: Config/BlockchainConfig/Blockchain-Dev.xcconfig
      Debug Production: Config/BlockchainConfig/Blockchain-Production.xcconfig
      Debug Staging: Config/BlockchainConfig/Blockchain-Staging.xcconfig
      Release: Config/BlockchainConfig/Blockchain-Production.xcconfig
      Release Staging: Config/BlockchainConfig/Blockchain-Staging.xcconfig
    dependencies:
    - sdk: libicucore.tbd
    - carthage: BigInt
    - carthage: Charts
    - carthage: keccak
    - carthage: LibWally
    - carthage: PhoneNumberKit
    - carthage: PromiseKit
    - carthage: RxCocoa
    - carthage: RxRelay
    - carthage: RxSwift
    - carthage: RxDataSources
    - carthage: Differentiator
    - carthage: scrypt
    - carthage: secp256k1
    - carthage: SocketIO
    - carthage: Starscream
    - carthage: stellarsdk
    - carthage: web3swift
    - carthage: WebRTC
    - carthage: Veriff
    - carthage: Zxcvbn
    - embed: false
      framework: Submodules/OpenSSL-for-iPhone/lib/libcrypto.a
    - target: PlatformUIKit
    - target: PlatformKit
    - target: ToolKit
    - target: NetworkKit
    - target: StellarKit
    - target: EthereumKit
    - target: ERC20Kit
    - target: BitcoinKit
    - target: HDWalletKit
    - target: CommonCryptoKit
    - target: Localization
    - carthage: FIRAnalyticsConnector
      findFrameworks: false
      linkType: static
    - carthage: FirebaseABTesting
      findFrameworks: false
      linkType: static
    - carthage: FirebaseAnalytics
      findFrameworks: false
      linkType: static
    - carthage: FirebaseCore
      findFrameworks: false
      linkType: static
    - carthage: FirebaseCoreDiagnostics
      findFrameworks: false
      linkType: static
    - carthage: FirebaseCrashlytics
      findFrameworks: false
      linkType: static
    - carthage: FirebaseDynamicLinks
      findFrameworks: false
      linkType: static
    - carthage: FirebaseInstallations
      findFrameworks: false
      linkType: static
    - carthage: FirebaseInstanceID
      findFrameworks: false
      linkType: static
    - carthage: FirebaseMessaging
      findFrameworks: false
      linkType: static
    - carthage: FirebaseRemoteConfig
      findFrameworks: false
      linkType: static
    - carthage: GoogleAppMeasurement
      findFrameworks: false
      linkType: static
    - carthage: GoogleDataTransport
      findFrameworks: false
      linkType: static
    - carthage: GoogleDataTransportCCTSupport
      findFrameworks: false
      linkType: static
    - carthage: GoogleUtilities
      findFrameworks: false
      linkType: static
    - carthage: nanopb
      findFrameworks: false
      linkType: static
    - carthage: PromisesObjC
      findFrameworks: false
      linkType: static
    - carthage: Protobuf
      findFrameworks: false
      linkType: static
    platform: iOS
    postBuildScripts:
    - inputFiles:
      - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
      name: Run Crashlytics
      script: ${PROJECT_DIR}/scripts/crashlytics/run
    postCompileScripts:
    - name: Swiftlint
      path: Blockchain/Scripts/swiftlint.sh
    - name: Setup Firebase Environment
      path: Blockchain/Scripts/firebase_copy_plist.sh
    - name: Envman BUILT_PRODUCTS_DIR
      path: Blockchain/Scripts/export_built_products_dir.sh
    settings:
      base:
        GCC_PREFIX_HEADER: Blockchain/Blockchain-Prefix.pch
        HEADER_SEARCH_PATHS:
        - $(PROJECT_DIR)/Submodules/OpenSSL-for-iPhone/include
        - $(PROJECT_DIR)/Submodules/SocketRocket
        LIBRARY_SEARCH_PATHS:
        - $(PROJECT_DIR)/Submodules/OpenSSL-for-iPhone/lib
        OTHER_LDFLAGS:
        - -ObjC
        SWIFT_OBJC_BRIDGING_HEADER: Blockchain/Blockchain-Bridging-Header.h
      configs:
        Debug Dev:
          groups:
          - debug_signing
          - base_ios
        Debug Production:
          groups:
          - debug_signing
          - base_ios
        Debug Staging:
          groups:
          - debug_signing
          - base_ios
        Release:
          groups:
          - release_signing
          - base_ios
        Release Staging:
          groups:
          - release_signing
          - base_ios
    sources:
    - group: Blockchain/JavaScript
      optional: true
      path: Submodules/My-Wallet-V3/dist/my-wallet.js
    - excludes:
      - Firebase
      - Scripts
      path: Blockchain
    - includes:
      - '**/*.[hm]'
      path: Submodules/SocketRocket/SocketRocket
    - includes:
      - BTCAddress.[hm]
      - BTCBase58.[hm]
      - BTCBigNumber.[hm]
      - BTCCurvePoint.[hm]
      - BTCData.[hm]
      - BTCErrors.[hm]
      - BTCKey.[hm]
      - BTCKeychain.[hm]
      - BTCNetwork.[hm]
      - BTCProtocolSerialization.[hm]
      - NSData+BTCData.[hm]
      path: Submodules/CoreBitcoin/CoreBitcoin
    type: application
  BlockchainTests:
    dependencies:
    - target: Blockchain
    - carthage: RxSwift
    - carthage: RxBlocking
    - carthage: RxTest
    platform: iOS
    sources:
    - BlockchainTests
    type: bundle.unit-test
  CommonCryptoKit:
    scheme:
      testTargets:
      - CommonCryptoKitTests
    templates:
    - Framework
  CommonCryptoKitTests:
    dependencies:
    - target: CommonCryptoKit
    templates:
    - FrameworkTest
  ERC20Kit:
    dependencies:
    - target: NetworkKit
    - target: EthereumKit
    - target: PlatformKit
    - carthage: RxCocoa
    - carthage: RxSwift
    - carthage: RxRelay
    - carthage: BigInt
    - carthage: web3swift
    scheme:
      testTargets:
      - ERC20KitTests
    templates:
    - Framework
  ERC20KitTests:
    dependencies:
    - target: ERC20Kit
    templates:
    - FrameworkTest
  EthereumKit:
    dependencies:
    - target: NetworkKit
    - target: PlatformKit
    - carthage: keccak
    - carthage: PromiseKit
    - carthage: BigInt
    - carthage: secp256k1
    - carthage: web3swift
    - carthage: scrypt
    - carthage: RxSwift
    - carthage: RxRelay
    scheme:
      testTargets:
      - EthereumKitTests
    templates:
    - Framework
  EthereumKitTests:
    dependencies:
    - target: EthereumKit
    templates:
    - FrameworkTest
  HDWalletKit:
    dependencies:
    - target: CommonCryptoKit
    - carthage: LibWally
    scheme:
      testTargets:
      - HDWalletKitTests
    templates:
    - Framework
  HDWalletKitTests:
    dependencies:
    - target: HDWalletKit
    templates:
    - FrameworkTest
  Localization:
    templates:
    - Framework
  NetworkKit:
    configFiles:
      Debug Dev: Config/NetworkKitConfig/NetworkKit-Dev.xcconfig
      Debug Production: Config/NetworkKitConfig/NetworkKit-Production.xcconfig
      Debug Staging: Config/NetworkKitConfig/NetworkKit-Staging.xcconfig
      Release: Config/NetworkKitConfig/NetworkKit-Production.xcconfig
      Release Staging: Config/NetworkKitConfig/NetworkKit-Staging.xcconfig
    dependencies:
    - carthage: RxSwift
    - target: ToolKit
    info:
      path: NetworkKit/Info.plist
      properties:
        API_URL: $(API_URL)
        BUY_WEBVIEW_URL: $(BUY_WEBVIEW_URL)
        EXCHANGE_URL: $(EXCHANGE_URL)
        EXPLORER_SERVER: $(EXPLORER_SERVER)
        PIN_CERTIFICATE: $(PIN_CERTIFICATE)
        RETAIL_CORE_SOCKET_URL: $(RETAIL_CORE_SOCKET_URL)
        RETAIL_CORE_URL: $(RETAIL_CORE_URL)
        WALLET_SERVER: $(WALLET_SERVER)
        WEBSOCKET_SERVER: $(WEBSOCKET_SERVER)
        WEBSOCKET_SERVER_BCH: $(WEBSOCKET_SERVER_BCH)
        WEBSOCKET_SERVER_ETH: $(WEBSOCKET_SERVER_ETH)
    platform: iOS
    postCompileScripts:
    - name: Get SSL Certificate
      path: NetworkKit/Scripts/get_ssl_certificate.sh
    scheme:
      testTargets:
      - NetworkKitTests
    sources:
    - excludes:
      - Scripts
      - Cert
      path: NetworkKit
    - buildPhase:
        copyFiles:
          destination: resources
      group: NetworkKit/Cert
      optional: true
      path: NetworkKit/Cert/blockchain.der
    type: framework
  NetworkKitTests:
    dependencies:
    - target: NetworkKit
    templates:
    - FrameworkTest
  PlatformKit:
    dependencies:
    - target: CommonCryptoKit
    - target: Localization
    - target: NetworkKit
    - target: ToolKit
    - carthage: BigInt
    - carthage: RxSwift
    - carthage: RxRelay
    - carthage: RxCocoa
    scheme:
      testTargets:
      - PlatformKitTests
    templates:
    - Framework
  PlatformKitTests:
    dependencies:
    - target: PlatformKit
    templates:
    - FrameworkTest
  PlatformUIKit:
    dependencies:
    - target: Localization
    - target: PlatformKit
    - target: ToolKit
    - carthage: BigInt
    - carthage: Charts
    - carthage: PhoneNumberKit
    - carthage: RxSwift
    - carthage: RxRelay
    - carthage: RxCocoa
    - carthage: Zxcvbn
    - carthage: RxDataSources
    - carthage: Differentiator
    scheme:
      testTargets:
      - PlatformUIKitTests
    templates:
    - Framework
  PlatformUIKitTests:
    dependencies:
    - target: PlatformUIKit
    templates:
    - FrameworkTest
  StellarKit:
    dependencies:
    - target: PlatformKit
    - carthage: RxCocoa
    - carthage: RxSwift
    - carthage: stellarsdk
    scheme:
      testTargets:
      - StellarKitTests
    templates:
    - Framework
  StellarKitTests:
    dependencies:
    - target: StellarKit
    templates:
    - FrameworkTest
  TestKit:
    templates:
    - Framework
  ToolKit:
    dependencies:
    - carthage: BigInt
    - carthage: RxSwift
    - carthage: RxRelay
    scheme:
      testTargets:
      - ToolKitTests
    templates:
    - Framework
  ToolKitTests:
    dependencies:
    - target: ToolKit
    templates:
    - FrameworkTest
